
server:
    port: 9010
    
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:9010/eureka/
spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://localhost:3306/yangyukun?useUnicode=true&characterEncoding=utf8
    username: YYK
    password: yangyukun
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

